---
title: "X-Road Analysis"
author: "Andrius Matšenas"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(c("httr", "jsonlite")) #install required packages
library(httr)
library(jsonlite)
library(tidyverse)
library(R.utils)
```

## Getting data from API

Documentation found here: https://github.com/ria-ee/X-Road-opmonitor/blob/master/docs/opendata/user_guide/ug_opendata_api.md

```{r get-request}
# Set up URL
baseURL <- "https://logs.x-tee.ee" # API domain
instance <- "/EE/api" # instance, currently only for EE (Estonia) but in the future e.g. FI (Finland)
requestType <- "/daily_logs" # request specification
date <- "2020-03-06"  # date for daily log
parameters <- paste0("?",
                     "date=", date)
call <- paste0(baseURL, instance, requestType, parameters) # final URL

# Getting details in API
get_results <- GET(url = call)

# Getting status of HTTP Call
status_code(get_results) # 2xx means success, 3xx client side error, 4xx server side error

# Saving result tar.gz file
tar_gz_filename <- paste0(date, ".tar.gz")
get_results %>% content("raw") %>% writeBin(tar_gz_filename)

# Unzip tar.gz
file <- tar_gz_filename %>% untar()
json_filename <- paste0(date, ".json")
data <- read.delim(file = file, sep="\t")
data <- fromJSON(file = json_filename)

#saving
# Save to file


# Draft
```

## Including Plots


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
